// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import Foundation
import Rswift
import UIKit

/// This `R` struct is code generated, and contains references to static resources.
struct R: Rswift.Validatable {
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    private init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    private init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    private init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 34 images.
  struct image {
    /// Image `bg5`.
    static let bg5 = ImageResource(bundle: _R.hostingBundle, name: "bg5")
    /// Image `btn_back_blue_nor`.
    static let btn_back_blue_nor = ImageResource(bundle: _R.hostingBundle, name: "btn_back_blue_nor")
    /// Image `btn_back_blue_sel`.
    static let btn_back_blue_sel = ImageResource(bundle: _R.hostingBundle, name: "btn_back_blue_sel")
    /// Image `btn_bg_fill_down`.
    static let btn_bg_fill_down = ImageResource(bundle: _R.hostingBundle, name: "btn_bg_fill_down")
    /// Image `btn_bg_fill_nor`.
    static let btn_bg_fill_nor = ImageResource(bundle: _R.hostingBundle, name: "btn_bg_fill_nor")
    /// Image `btn_line`.
    static let btn_line = ImageResource(bundle: _R.hostingBundle, name: "btn_line")
    /// Image `btn_line_down`.
    static let btn_line_down = ImageResource(bundle: _R.hostingBundle, name: "btn_line_down")
    /// Image `button_blue_bg_down`.
    static let button_blue_bg_down = ImageResource(bundle: _R.hostingBundle, name: "button_blue_bg_down")
    /// Image `button_blue_bg_normal`.
    static let button_blue_bg_normal = ImageResource(bundle: _R.hostingBundle, name: "button_blue_bg_normal")
    /// Image `checkmark`.
    static let checkmark = ImageResource(bundle: _R.hostingBundle, name: "checkmark")
    /// Image `cross`.
    static let cross = ImageResource(bundle: _R.hostingBundle, name: "cross")
    /// Image `guide1`.
    static let guide1 = ImageResource(bundle: _R.hostingBundle, name: "guide1")
    /// Image `guide2`.
    static let guide2 = ImageResource(bundle: _R.hostingBundle, name: "guide2")
    /// Image `guide3`.
    static let guide3 = ImageResource(bundle: _R.hostingBundle, name: "guide3")
    /// Image `guide4`.
    static let guide4 = ImageResource(bundle: _R.hostingBundle, name: "guide4")
    /// Image `guide4_2`.
    static let guide4_2 = ImageResource(bundle: _R.hostingBundle, name: "guide4_2")
    /// Image `LOGO`.
    static let lOGO = ImageResource(bundle: _R.hostingBundle, name: "LOGO")
    /// Image `launcher`.
    static let launcher = ImageResource(bundle: _R.hostingBundle, name: "launcher")
    /// Image `loading1`.
    static let loading1 = ImageResource(bundle: _R.hostingBundle, name: "loading1")
    /// Image `loading2`.
    static let loading2 = ImageResource(bundle: _R.hostingBundle, name: "loading2")
    /// Image `loading3`.
    static let loading3 = ImageResource(bundle: _R.hostingBundle, name: "loading3")
    /// Image `loading4`.
    static let loading4 = ImageResource(bundle: _R.hostingBundle, name: "loading4")
    /// Image `loading5`.
    static let loading5 = ImageResource(bundle: _R.hostingBundle, name: "loading5")
    /// Image `loading6`.
    static let loading6 = ImageResource(bundle: _R.hostingBundle, name: "loading6")
    /// Image `loading7`.
    static let loading7 = ImageResource(bundle: _R.hostingBundle, name: "loading7")
    /// Image `progress_activity`.
    static let progress_activity = ImageResource(bundle: _R.hostingBundle, name: "progress_activity")
    /// Image `progress_circular`.
    static let progress_circular = ImageResource(bundle: _R.hostingBundle, name: "progress_circular")
    /// Image `qidongbeijing`.
    static let qidongbeijing = ImageResource(bundle: _R.hostingBundle, name: "qidongbeijing")
    /// Image `signup_btn_line_down`.
    static let signup_btn_line_down = ImageResource(bundle: _R.hostingBundle, name: "signup_btn_line_down")
    /// Image `signup_btn_line_nor`.
    static let signup_btn_line_nor = ImageResource(bundle: _R.hostingBundle, name: "signup_btn_line_nor")
    /// Image `signup_line_btn_down`.
    static let signup_line_btn_down = ImageResource(bundle: _R.hostingBundle, name: "signup_line_btn_down")
    /// Image `signup_line_btn_nor`.
    static let signup_line_btn_nor = ImageResource(bundle: _R.hostingBundle, name: "signup_line_btn_nor")
    /// Image `signup_logo`.
    static let signup_logo = ImageResource(bundle: _R.hostingBundle, name: "signup_logo")
    /// Image `transparent_bg`.
    static let transparent_bg = ImageResource(bundle: _R.hostingBundle, name: "transparent_bg")
    
    /// `UIImage(named: "bg5", bundle: ..., traitCollection: ...)`
    static func bg5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.bg5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "btn_back_blue_nor", bundle: ..., traitCollection: ...)`
    static func btn_back_blue_nor(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.btn_back_blue_nor, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "btn_back_blue_sel", bundle: ..., traitCollection: ...)`
    static func btn_back_blue_sel(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.btn_back_blue_sel, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "btn_bg_fill_down", bundle: ..., traitCollection: ...)`
    static func btn_bg_fill_down(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.btn_bg_fill_down, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "btn_bg_fill_nor", bundle: ..., traitCollection: ...)`
    static func btn_bg_fill_nor(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.btn_bg_fill_nor, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "btn_line", bundle: ..., traitCollection: ...)`
    static func btn_line(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.btn_line, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "btn_line_down", bundle: ..., traitCollection: ...)`
    static func btn_line_down(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.btn_line_down, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_blue_bg_down", bundle: ..., traitCollection: ...)`
    static func button_blue_bg_down(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_blue_bg_down, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_blue_bg_normal", bundle: ..., traitCollection: ...)`
    static func button_blue_bg_normal(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_blue_bg_normal, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "checkmark", bundle: ..., traitCollection: ...)`
    static func checkmark(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.checkmark, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "cross", bundle: ..., traitCollection: ...)`
    static func cross(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.cross, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "guide1", bundle: ..., traitCollection: ...)`
    static func guide1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.guide1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "guide2", bundle: ..., traitCollection: ...)`
    static func guide2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.guide2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "guide3", bundle: ..., traitCollection: ...)`
    static func guide3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.guide3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "guide4", bundle: ..., traitCollection: ...)`
    static func guide4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.guide4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "guide4_2", bundle: ..., traitCollection: ...)`
    static func guide4_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.guide4_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "LOGO", bundle: ..., traitCollection: ...)`
    static func lOGO(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.lOGO, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "launcher", bundle: ..., traitCollection: ...)`
    static func launcher(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.launcher, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading1", bundle: ..., traitCollection: ...)`
    static func loading1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading2", bundle: ..., traitCollection: ...)`
    static func loading2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading3", bundle: ..., traitCollection: ...)`
    static func loading3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading4", bundle: ..., traitCollection: ...)`
    static func loading4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading5", bundle: ..., traitCollection: ...)`
    static func loading5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading6", bundle: ..., traitCollection: ...)`
    static func loading6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "loading7", bundle: ..., traitCollection: ...)`
    static func loading7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.loading7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "progress_activity", bundle: ..., traitCollection: ...)`
    static func progress_activity(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.progress_activity, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "progress_circular", bundle: ..., traitCollection: ...)`
    static func progress_circular(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.progress_circular, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qidongbeijing", bundle: ..., traitCollection: ...)`
    static func qidongbeijing(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qidongbeijing, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "signup_btn_line_down", bundle: ..., traitCollection: ...)`
    static func signup_btn_line_down(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.signup_btn_line_down, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "signup_btn_line_nor", bundle: ..., traitCollection: ...)`
    static func signup_btn_line_nor(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.signup_btn_line_nor, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "signup_line_btn_down", bundle: ..., traitCollection: ...)`
    static func signup_line_btn_down(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.signup_line_btn_down, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "signup_line_btn_nor", bundle: ..., traitCollection: ...)`
    static func signup_line_btn_nor(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.signup_line_btn_nor, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "signup_logo", bundle: ..., traitCollection: ...)`
    static func signup_logo(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.signup_logo, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "transparent_bg", bundle: ..., traitCollection: ...)`
    static func transparent_bg(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.transparent_bg, compatibleWithTraitCollection: traitCollection)
    }
    
    private init() {}
  }
  
  private struct intern: Rswift.Validatable {
    static func validate() throws {
      try _R.validate()
    }
    
    private init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    private init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    private init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 1 view controllers.
  struct segue {
    /// This struct is generated for `RegisterViewController`, and contains static references to 1 segues.
    struct registerViewController {
      /// Segue identifier `RegisterNext`.
      static let registerNext: StoryboardSegueIdentifier<UIStoryboardSegue, RegisterViewController, RegisterNextViewController> = StoryboardSegueIdentifier(identifier: "RegisterNext")
      
      /// Optionally returns a typed version of segue `RegisterNext`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func registerNext(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, RegisterViewController, RegisterNextViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.registerViewController.registerNext, segue: segue)
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.main)
    }
    
    private init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    private init() {}
  }
  
  private init() {}
}

struct _R: Rswift.Validatable {
  static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(NSLocale.init) ?? NSLocale.currentLocale()
  static let hostingBundle = NSBundle(identifier: "com.angcyo.AIOwnDemo") ?? NSBundle.mainBundle()
  
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    private init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIViewController
      
      let bundle = _R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIImage(named: "guide2") == nil { throw ValidationError(description: "[R.swift] Image named 'guide2' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if UIImage(named: "launcher") == nil { throw ValidationError(description: "[R.swift] Image named 'launcher' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
      
      private init() {}
    }
    
    struct main: StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = NavLauncherViewController
      
      let bundle = _R.hostingBundle
      let guide1ID = StoryboardViewControllerResource<UIViewController>(identifier: "Guide1ID")
      let guide2ID = StoryboardViewControllerResource<UIViewController>(identifier: "Guide2ID")
      let guide3ID = StoryboardViewControllerResource<UIViewController>(identifier: "Guide3ID")
      let guide4ID = StoryboardViewControllerResource<LastViewController>(identifier: "Guide4ID")
      let guideStoryboardID = StoryboardViewControllerResource<Guide2PageViewcontroller>(identifier: "GuideStoryboardID")
      let loginViewController = StoryboardViewControllerResource<LoginViewController>(identifier: "LoginViewController")
      let name = "Main"
      let registerViewController = StoryboardViewControllerResource<RegisterViewController>(identifier: "RegisterViewController")
      let testID = StoryboardViewControllerResource<TestViewController>(identifier: "TestID")
      
      func guide1ID(_: Void) -> UIViewController? {
        return UIStoryboard(resource: self).instantiateViewController(guide1ID)
      }
      
      func guide2ID(_: Void) -> UIViewController? {
        return UIStoryboard(resource: self).instantiateViewController(guide2ID)
      }
      
      func guide3ID(_: Void) -> UIViewController? {
        return UIStoryboard(resource: self).instantiateViewController(guide3ID)
      }
      
      func guide4ID(_: Void) -> LastViewController? {
        return UIStoryboard(resource: self).instantiateViewController(guide4ID)
      }
      
      func guideStoryboardID(_: Void) -> Guide2PageViewcontroller? {
        return UIStoryboard(resource: self).instantiateViewController(guideStoryboardID)
      }
      
      func loginViewController(_: Void) -> LoginViewController? {
        return UIStoryboard(resource: self).instantiateViewController(loginViewController)
      }
      
      func registerViewController(_: Void) -> RegisterViewController? {
        return UIStoryboard(resource: self).instantiateViewController(registerViewController)
      }
      
      func testID(_: Void) -> TestViewController? {
        return UIStoryboard(resource: self).instantiateViewController(testID)
      }
      
      static func validate() throws {
        if UIImage(named: "guide2") == nil { throw ValidationError(description: "[R.swift] Image named 'guide2' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "btn_bg_fill_down") == nil { throw ValidationError(description: "[R.swift] Image named 'btn_bg_fill_down' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "signup_btn_line_down") == nil { throw ValidationError(description: "[R.swift] Image named 'signup_btn_line_down' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "transparent_bg") == nil { throw ValidationError(description: "[R.swift] Image named 'transparent_bg' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "guide3") == nil { throw ValidationError(description: "[R.swift] Image named 'guide3' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "guide4_2") == nil { throw ValidationError(description: "[R.swift] Image named 'guide4_2' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "signup_btn_line_nor") == nil { throw ValidationError(description: "[R.swift] Image named 'signup_btn_line_nor' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_blue_bg_down") == nil { throw ValidationError(description: "[R.swift] Image named 'button_blue_bg_down' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "btn_bg_fill_nor") == nil { throw ValidationError(description: "[R.swift] Image named 'btn_bg_fill_nor' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "signup_logo") == nil { throw ValidationError(description: "[R.swift] Image named 'signup_logo' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "guide1") == nil { throw ValidationError(description: "[R.swift] Image named 'guide1' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_blue_bg_normal") == nil { throw ValidationError(description: "[R.swift] Image named 'button_blue_bg_normal' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "launcher") == nil { throw ValidationError(description: "[R.swift] Image named 'launcher' is used in storyboard 'Main', but couldn't be loaded.") }
        if _R.storyboard.main().testID() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'testID' could not be loaded from storyboard 'Main' as 'TestViewController'.") }
        if _R.storyboard.main().guide1ID() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'guide1ID' could not be loaded from storyboard 'Main' as 'UIViewController'.") }
        if _R.storyboard.main().guideStoryboardID() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'guideStoryboardID' could not be loaded from storyboard 'Main' as 'Guide2PageViewcontroller'.") }
        if _R.storyboard.main().loginViewController() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'loginViewController' could not be loaded from storyboard 'Main' as 'LoginViewController'.") }
        if _R.storyboard.main().registerViewController() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'registerViewController' could not be loaded from storyboard 'Main' as 'RegisterViewController'.") }
        if _R.storyboard.main().guide2ID() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'guide2ID' could not be loaded from storyboard 'Main' as 'UIViewController'.") }
        if _R.storyboard.main().guide3ID() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'guide3ID' could not be loaded from storyboard 'Main' as 'UIViewController'.") }
        if _R.storyboard.main().guide4ID() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'guide4ID' could not be loaded from storyboard 'Main' as 'LastViewController'.") }
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  private init() {}
}